version: "3.5"

services:
  postgresql:
    build: .
    container_name: microservice
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres